import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";


const BASE_URL = "https://instagram-nrdh.onrender.com/api/";


export const InstaApis = createApi({
  reducerPath: "api", 
  baseQuery: fetchBaseQuery({
    baseUrl: BASE_URL,
  }),
  tagTypes: ["USER", "PRODUCT"], 
  endpoints: (builder) => ({
  
    postNewUser: builder.mutation({
      query: (credentials) => ({
        url: "/user-login",
        method: "post",
        headers: { "Content-Type": "application/json" },
        body: credentials,
      }),
      invalidatesTags: ["USER"], 
    }),
   
    getProducts: builder.query({
      query: () => "products",
      providesTags: ["PRODUCT"], 
    }),
  }),
});

// Export hooks generated by createApi for the endpoints
export const { usePostNewUserMutation, useGetProductsQuery } = InstaApis;




